package scottie.cs301.EpicActuals.Resources.Cards;

import scottie.cs301.EpicActuals.Resources.Cards.CardActuals.Placeholder;
import scottie.cs301.EpicActuals.Resources.Cards.CardActuals.CardActualExampleForAlpha;
import scottie.cs301.EpicActuals.Resources.Cards.CardActuals.SCHOOL;
import scottie.cs301.Imports.GameFramework.R;

/**
 * Created by Zimmerms18 on 3/30/2016.
 * <p/>
 * For use in Epic Spell Wars cs301 class project.
 * Team 5: Scott Zimmerman, Markus Perry, Liz Mukai, Teresa Condon
 * <p/>
 * Deck object as a simple container for Card objects.
 * Done so that LocalGameActual can have a static final array of cards.
 * So a card may be accessed by LocalGameActual.DECK.theDeck[cardID].
 */
public
class Deck
    {
        public static final Card[] theDeck = {
                new Placeholder(),
                //myID, myInit, myPlace, myImage, mySchool
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),
                new CardActualExampleForAlpha(1, 19 , 3 , R.drawable.bedazzlement , SCHOOL.Illusion),
                new CardActualExampleForAlpha(2, 0, 1 , R.drawable.benvoodoo, SCHOOL.Dark),
                new CardActualExampleForAlpha(3, 15, 3 , R.drawable.brainsuck, SCHOOL.Illusion),
                new CardActualExampleForAlpha(4, 0, 2, R.drawable.catastrophic, SCHOOL.Illusion),
                new CardActualExampleForAlpha(5, 3, 3, R.drawable.chicken, SCHOOL.Elemental),
                new CardActualExampleForAlpha(6, 4, 3, R.drawable.coneofacid, SCHOOL.Arcane),
                new CardActualExampleForAlpha(7, 0, 1, R.drawable.pamandbecubas, SCHOOL.Illusion),
                new CardActualExampleForAlpha(8, 0, 1, R.drawable.professorpresto, SCHOOL.Arcane),
                new CardActualExampleForAlpha(9, 0, 1, R.drawable.scorchia, SCHOOL.Elemental),
                new CardActualExampleForAlpha(10, 0, 1, R.drawable.thaifoon, SCHOOL.Elemental),
                new CardActualExampleForAlpha(11, 0, 1, R.drawable.thedeathfairy, SCHOOL.Dark),
                new CardActualExampleForAlpha(12, 0, 2, R.drawable.twofaced, SCHOOL.Arcane),

        };
    }
